In [ ]:
# 1. Write a Python program to check if a given number is positive or negative.

In [8]:
number=int(input("Enter the number:"))
if(number>0):
    print("The number is positive")
else:
    if(number<0):
        print("The number is negative")
    else:
        print("The number is neither positive nor negative.")
    

Enter the number: 0


The number is neither positive nor negative.


In [ ]:
# 2. Create a program that determines if a person is eligible to vote based on their age.

In [7]:
age=int(input("Enter the age:"))
if(age>=18):
    print("You are eligible to vote.")
else:
    print("You are not eligible to vote.")

Enter the age: 18


You are eligible to vote.


In [ ]:
# 3. Develop a program to find the maximum of two numbers using if-else statements.

In [14]:
a=int(input("Enter the first number:"))
b=int(input("Enter the second number:"))
if(a>b):
    print(str(a)+" is greater number than  "+str(b))
else:
     print(str(b)+" is greater number than "+str(a))

Enter the first number: 23
Enter the second number: 1


23 is greater number than  1


In [ ]:
# 4. Write a Python script to classify a given year as a leap year or not.

In [52]:

# Python program to check if year is a leap year or not

year =2000

# To get year (integer input) from the user
# year = int(input("Enter a year: "))

# divided by 100 means century year (ending with 00)
# century year divided by 400 is leap year
if (year % 400 == 0) and (year % 100 == 0):
    print("{0} is a leap year".format(year))

# not divided by 100 means not a century year
# year divided by 4 is a leap year
elif (year % 4 ==0) and (year % 100 != 0):
    print("{0} is a leap year".format(year))

# if not divided by both 400 (century year) and 4 (not century year)
# year is not leap year
else:
    print("{0} is not a leap year".format(year))        
       

2000 is a leap year


In [ ]:
# 5. Create a program that checks whether a character is a vowel or a consonant.

In [31]:
character=input("Enter the character : ")
if(character=='a' or character=='e'  or character=='i' or character=='o' or character=='u'):
    print("The character is a vowel ")
else:
     print("The character is a consonant")         

Enter the character :  i


The character is a vowel 


In [ ]:
# 6. Implement a program to determine whether a given number is even or odd.

In [34]:
number=int(input("Enter the number:"))
if number%2==0:
    print("The number is even ")
else:
    print("The number is odd")

Enter the number: 7


The number is odd


In [ ]:
# 7. Write a Python function to calculate the absolute value of a number without using the `abs()` function.

In [1]:
number=int(input("Enter the number:"))
if number>0:
    print(number)
else:
    print(-number)

Enter the number: -78


78


In [ ]:
# 8. Develop a program that determines the largest of three given numbers using if-else statements.

In [5]:
a=int(input("Enter the number 1:"))
b=int(input("Enter the number 2:"))
c=int(input("Enter the number 3:"))
# if(a>b and a>c):
#     print(str(a)+" is greatest of three number" )
# elif(b>a and b>c):
#     print(str(b)+" is greatest of three number" )
# else:
#      print(str(c)+" is greatest of three number" )
if(a>b and a>c):
    print(str(a)+" is greatest of three number" )
else:
    if((b>a and b>c)):
         print(str(b)+" is greatest of three number" )
    
    else:
         print(str(c)+" is greatest of three number" )


Enter the number 1: 5
Enter the number 2: 8
Enter the number 3: 9


9 is greatest of three number


In [ ]:
# 9. Create a program that checks if a given string is a palindrome.

In [53]:
string=input("Enter the string:")
if(string==string[::-1]):
    print(f" Yes, {string} is a pallindrome ")
else:
     print(f" No, {string} is not a pallindrome ")

Enter the string: level


 Yes, level is a pallindrome 


In [ ]:
# 10. Write a Python program to calculate the grade based on a student's score.

In [69]:
score=float(input("Enter your percent score"))
if(score>90):
    print("Excellent, You scored A+ grade")
elif(85<score<=90):
     print("Very good, You scored A grade")
elif(80<score<=85):
     print("Good,You scored B+ grade")
elif(75<score<=80):
     print("Above average, You scored B grade")
elif(70<score<=75):
     print("Average,You scored C+ grade")
elif(65<score<=70):
     print("Average,You scored C grade")
elif(60<score<=65):
     print("Average,You scored D+ grade")
elif(55<score<=60):
     print("Poor,You scored D grade")
elif(50<score<=55):
     print("Very Poor,You scored E+ grade")
elif(45<score<=50):
     print("Very very Poor,You scored E grade")
elif(score<=45):
     print("Failed! You scored F grade")


Enter your percent score 83.5


Good,You scored B+ grade


In [ ]:
# 11. Write a program to find the largest among three numbers using nested if-else statements.

In [1]:
a=int(input("Enter the 1st number :"))
b=int(input("Enter the 2nd number :"))
c=int(input("Enter the 3rd number :"))
if(a>b):
    if(a>c):
        print(str(a)+" is the greatest number ")
    else:
        print(str(c)+" is the greatest number ")
else:
    if(b>c):
        print(str(b)+" is the greatest number ")
    else:
        print(str(c)+" is the greatest number ")
        

Enter the 1st number : 5
Enter the 2nd number : 7
Enter the 3rd number : 9


9 is the greatest number 


In [ ]:
# 12. Implement a program to determine if a triangle is equilateral, isosceles, or scalene.

In [11]:
side_1=int(input("Enter the side 1 length:"))
side_2=int(input("Enter the side 2 length:"))
side_3=int(input("Enter the side 3 length:"))
if(side_1==side_2):
    if(side_1==side_3):
        print("The triangle is equilateral .")
    else:
        print("The triangle is isosceles .")
else:
    if(side_1!=side_2):
        if(side_1==side_3):
            print("The triangle is isosceles .")
        else:
             print("The triangle is scalene.")

Enter the side 1 length: 5
Enter the side 2 length: 5
Enter the side 3 length: 5


The triangle is equilateral .


In [ ]:
# 13. Develop a program that checks if a year is a leap year and also if it is a century year.

In [57]:
# Python program to check if year is a leap year or not

year =600

# To get year (integer input) from the user
# year = int(input("Enter a year: "))

# divided by 100 means century year (ending with 00)
# century year divided by 400 is leap year
if (year % 400 == 0) and (year % 100 == 0):
    print("{0} is a leap year".format(year))

# not divided by 100 means not a century year
# year divided by 4 is a leap year
elif (year % 4 ==0) and (year % 100 != 0):
    print("{0} is a leap year".format(year))

# if not divided by both 400 (century year) and 4 (not century year)
# year is not leap year
else:
    print("{0} is not a leap year".format(year))
    
    
    
if(year%100==0):
    print("Yes,",year,"is a century year ")
else:
    print("No,",year," is not a century year")

600 is not a leap year
Yes, 600 is a century year 


In [ ]:
# 14. Write a Python script to determine if a number is positive, negative, or zero.

In [16]:
num=int(input("Enter the number:"))
if(num>0):
    print(str(num)+" is positive")
else:
    if(num<0):
        print(str(num) +" is negative.")
    else:
        print("The number is zero .")

Enter the number: -11


-11 is negative.


In [ ]:
# 15. Create a program to check if a person is a teenager (between 13 and 19 years old).

In [32]:
age=int(input("Enter your age:"))
if(age>13):
        if(age<19):
                print("Yes, you are a teenager .")
        else:
                print("No, you are not a teenager .")
else:
    print("No, you are not teenager .")

Enter your age: 19


No, you are not a teenager .


In [ ]:
# 16. Develop a program that determines the type of angle based on its measure (acute, obtuse, or right).

In [35]:
angle=int(input("Enter the value of angle in degrees :"))
if(angle>90):
    print("The angle is obtuse")
else:
    if(angle<90):
        print("The angle is acute.")
    else:
        print("The angle is right .")

Enter the value of angle in degrees : 90


The angle is right .


In [ ]:
# 17. Write a Python program to calculate the roots of a quadratic equation.

In [42]:
print("Quadratic equation is ax^2 + bx+ c=0 ")
a=int(input("Enter the value of a which is coefficient of x^2 :"))
b=int(input("Enter the value of b which is coefficient of x:"))
c=int(input("Enter the value of c constant term:"))
x1=((-b)+((b)**2 -4*a*c)**0.5)/(2*a)
x2=((-b)-((b)**2 -4*a*c)**0.5)/(2*a)
print(f"Roots  of Quadratic equation {a}x^2 +{b}x +{c} = 0 are {x1} and {x2}")

Quadratic equation is ax^2 + bx+ c=0 


Enter the value of a which is coefficient of x^2 : 1
Enter the value of b which is coefficient of x: 3
Enter the value of c constant term: 2


Roots  of Quadratic equation 1x^2 +3x +2 = 0 are -1.0 and -2.0


In [ ]:
18. Implement a program to determine the day of the week based on a user-provided number (1 for Monday, 2for Tuesday, etc.).

In [28]:
n=int(input("Enter the number:"))
if(n==1):
    print("It is Monday")
else:
    if(n==2):
         print("It is Tuesday")
    else:
        if(n==3):
            print("It is Wednesday")
        else:
                
                if(n==4):
                    print("It is Thrusday")
                else:
                    if(n==5):
                        print("It is Friday")
                    else:
                        if(n==6):
                            print("It is Saturday")
                        else:
                            print("It is Sunday")
        

Enter the number: 2


It is Tuesday


In [ ]:
# 19. Create a program that determines if a year is a leap year and also if it is evenly divisible by 400.

In [2]:
# Python program to check if year is a leap year or not

year =2000


# To get year (integer input) from the user
# year = int(input("Enter a year: "))

# divided by 100 means century year (ending with 00)
# century year divided by 400 is leap year
if (year % 400 == 0) and (year % 100 == 0):
    print("{0} is a leap year ".format(year))

# not divided by 100 means not a century year
# year divided by 4 is a leap year
elif (year % 4 ==0) and (year % 100 != 0):
    print("{0} is a leap year".format(year))

# if not divided by both 400 (century year) and 4 (not century year)
# year is not leap year
else:
    print("{0} is not a leap year".format(year))

2000 is a leap year 


In [ ]:
# 20. Develop a program that checks if a given number is prime or not using nested if-else statements.

In [45]:
# Number to be checked for prime

n=5

# Check if the number is greater than 1

if n > 1:
    for i in range(2, int(n/2)+1):
	    if (n % i) == 0:
	            print(n, "is not a prime number")
	            break
	    else:
		        print(n, "is a prime number")
                
# If the number is less than 1, its also not a prime number.
else:
	print(n, "is not a prime number")

5 is a prime number


In [ ]:
# 21. Write a Python program to assign grades based on different ranges of scores using elif statements.

In [18]:
score=float(input("Enter your percent score"))
if(score>90):
    print("Excellent, You scored A+ grade")
elif(85<score<=90):
     print("Very good, You scored A grade")
elif(80<score<=85):
     print("Good,You scored B+ grade")
elif(75<score<=80):
     print("Above average, You scored B grade")
elif(70<score<=75):
     print("Average,You scored C+ grade")
elif(65<score<=70):
     print("Average,You scored C grade")
elif(60<score<=65):
     print("Average,You scored D+ grade")
elif(55<score<=60):
     print("Poor,You scored D grade")
elif(50<score<=55):
     print("Very Poor,You scored E+ grade")
elif(45<score<=50):
     print("Very very Poor,You scored E grade")
elif(score<=45):
     print("Failed! You scored F grade")

Enter your percent score 84


Good,You scored B+ grade


In [ ]:
# 22. Implement a program to determine the type of a triangle based on its angles.

In [23]:
angle_1=int(input("Enter the value of first angle in degrees :"))
angle_2=int(input("Enter the value of second angle in degrees :"))
angle_3=int(input("Enter the value of third angle in degrees :"))
if(angle_1==angle_2==angle_3):
    print("It is equilateral triangle")
elif(angle_1==angle_2!=angle_3 or angle_1!=angle_2==angle_3 or angle_1==angle_3!=angle_22):
   
        print("It is isosceles triangle")
elif(angle_1!=angle_2!=angle_3):
    print("It is scalene triangle.")

Enter the value of first angle in degrees : 90
Enter the value of second angle in degrees : 45
Enter the value of third angle in degrees : 45


It is isosceles triangle


In [ ]:
# 23. Develop a program to categorize a given person's BMI into underweight, normal, overweight, or obese using elif statements.

In [16]:



bmi=float(input("Enter your BMI :"))
if(bmi<18.5):
        print("You are underweight ")
elif(bmi>=18.5 and bmi<25):
        print("You are normal ")
elif(bmi>=25 and bmi<30):
        print("You are overweight ")
elif(bmi>=30):
        print("You are obese ")
        

Enter your BMI : 24.98


You are normal 


In [ ]:
# 24. Create a program that determines whether a given number is positive, negative, or zero using elif
# statements.

In [19]:
num=int(input("Enter the number:"))
if(num>0):
    print(str(num)+" is positive")
elif(num<0):
        print(str(num) +" is negative.")
elif(num==0):
        print("The number is zero .")

Enter the number: 0


The number is zero .


In [21]:
# 25. Write a Python script to determine the type of a character (uppercase, lowercase, or special) using elif statements.

In [5]:
char=input("Enter the character :")
if(char.isupper()):
    print("It is uppercase character")
elif(char.islower()):
    print("It is lowercase character")
elif(char.isalnum()==False):
    print("It is special character")

Enter the character : GO


It is uppercase character


In [ ]:
# 26. Implement a program to calculate the discounted price based on different purchase amounts using elif statements

In [14]:
p=int(input('Enter purchase amount: '))

if p<=5000:
    dis=0
elif p>5000 and p<=10000:
    dis=(p-5000)*(10/100.0)
elif p>10000 and p<=20000:
    dis=(p-10000)*(20/100.0)
elif p>20000 and p<=30000:
    dis=(p-20000)*(30/100.0)
else:
    dis=(p-30000)*(40/100.0)

print('Discount Amount = {:.2f}'.format(dis))
print('Net Bill Amount = {:.2f}'.format(p-dis))

Enter purchase amount:  9000


Discount Amount = 400.00
Net Bill Amount = 8600.00


In [ ]:
# 27. Develop a program to calculate the electricity bill based on different consumption slabs using elif statements.

In [21]:
def calculateBill(units):
 

    if (units <= 100):
      
        return units * 10;
     
    elif (units <= 200):
     
        return ((100 * 10) +
                (units - 100) * 15);
     
    elif (units <= 300):
      
        return ((100 * 10) +
                (100 * 15) +
                (units - 200) * 20);
     
    elif (units > 300):
     
        return ((100 * 10) +
                (100 * 15) +
                (100 * 20) +
                (units - 300) * 25);
     
    return 0;
 
units=300
print(f"The net electricity bill is for {units} units consumed is Rs.{calculateBill(units)}")
 

The net electricity bill is for 300 units consumed is Rs.4500


In [ ]:
# 28. Create a program to determine the type of quadrilateral based on its angles and sides using elif statements.

In [11]:
a=float(input("Enter the angle 1:"))
b=float(input("Enter the angle 2:"))
c=float(input("Enter the angle 3:"))
d=float(input("Enter the angle 4:"))
ab=float(input("Enter the side 1:"))
bc=float(input("Enter the side 2:"))
cd=float(input("Enter the side 3:"))
ad=float(input("Enter the side 4:"))
if(a==b==c==d==90 and ab==bc==cd==ad):
    print("The given quadrilateral is a square.")
elif(a==b==c==d==90 and   ab==cd and bc==ad ):
                          # or(ab==bc and cd ==ad) or(ab==ad and bc==cd))):
    print("The given quadrilateral is a rectangle.")
elif(ab==cd==bc==ad):
    print("The given quadrilateral is a rhombus.")
# elif(a==b==c==d==90 and ab==cd and bc==ad):
#     print("The given quadrilateral is a square.")
elif( ab==cd and bc==ad) :
    print("The given quadrilateral is a parallelogram.")
else:
    print("it is simple quadrilateral")
    


Enter the angle 1: 90
Enter the angle 2: 90
Enter the angle 3: 90
Enter the angle 4: 90
Enter the side 1: 12
Enter the side 2: 12
Enter the side 3: 144
Enter the side 4: 144


it is simple quadrilateral


In [ ]:
# 29. Write a Python script to determine the season based on a user-provided month using elif statements.

In [4]:

month = input("Input the month (e.g. January, February etc.): ")

if month in ('November','December','January', 'February'):
	season = 'winter'
elif month in ( 'March','April'):
	season = 'spring'
elif month in ( 'May','June','July'):
	season = 'summer'
elif month in (  'August', 'September','October'):
	season = 'autumn'

print("Season is",season)


Input the month (e.g. January, February etc.):  April


Season is spring


In [ ]:
# 30. Implement a program to determine the type of a year (leap or common) and month (30 or 31 days) using
# elif statements

In [25]:
month = int(input("Enter the month: "))
year = int(input("Enter the year: "))
if(month == 1 or month == 3 or month == 5 or month == 7 or month == 8 or month == 10 or month == 12):
	print("Number of days is 31")
elif((month == 2) and ((year%400==0) or (year%4==0 and year%100!=0))):	
	print("Number of days is 29")
elif(month == 2):
	print(" of days is 28")
else:
	print("Number of days is 30")
    
if (year % 400 == 0) and (year % 100 == 0):
    print("{0} is a leap year ".format(year))

# not divided by 100 means not a century year
# year divided by 4 is a leap year
elif (year % 4 ==0) and (year % 100 != 0):
    print("{0} is a leap year".format(year))

# if not divided by both 400 (century year) and 4 (not century year)
# year is not leap year
else:
    print("{0} is not a leap year.It is a common year.".format(year))    
    
    


Enter the month:  9
Enter the year:  2023


Number of days is 30
2023 is not a leap year.It is a common year.


In [ ]:
# 1. Write a Python program that checks if a given number is positive, negative, or zero.

In [5]:
number=int(input("Enter the number:"))
if(number>0):
    print("The number is positive")
else:
    if(number<0):
        print("The number is negative")
    else:
        print("The number is zero")
    

Enter the number: -123


The number is negative


In [ ]:
# 2. Create a program to determine if a person is eligible to vote based on their age.

In [10]:
age=int(input("Enter your age:"))
if(age>=18):
      print("You are eligible to vote")
else:
      print("You are not eligible to vote")

Enter your age: 90


You are eligible to vote


In [ ]:
# 3. Write a program to find the maximum of two given numbers using conditional statements.

In [18]:
a=7
b=40
if(a>b):
    print(f"Maximum of {a} and {b} is {a}")
else:
    print(f"Maximum of {a} and {b} is {b}")

Maximum of 7 and 40 is 40


In [ ]:
# 4. Develop a program that calculates the grade of a student based on their exam score.

In [21]:
score=float(input("Enter your percent score:"))
if(score>90):
    print("Excellent, You scored A+ grade")
elif(85<score<=90):
     print("Very good, You scored A grade")
elif(80<score<=85):
     print("Good,You scored B+ grade")
elif(75<score<=80):
     print("Above average, You scored B grade")
elif(70<score<=75):
     print("Average,You scored C+ grade")
elif(65<score<=70):
     print("Average,You scored C grade")
elif(60<score<=65):
     print("Average,You scored D+ grade")
elif(55<score<=60):
     print("Poor,You scored D grade")
elif(50<score<=55):
     print("Very Poor,You scored E+ grade")
elif(45<score<=50):
     print("Very very Poor,You scored E grade")
elif(score<=45):
     print("Failed! You scored F grade")

Enter your percent score: 95


Excellent, You scored A+ grade


In [ ]:
# 5. Create a program that checks if a year is a leap year or not.

In [10]:

# Python program to check if year is a leap year or not

year =2004

# To get year (integer input) from the user
# year = int(input("Enter a year: "))

# divided by 100 means century year (ending with 00)
# century year divided by 400 is leap year
if (year % 400 == 0) and (year % 100 == 0):
    print("{0} is a leap year".format(year))

# not divided by 100 means not a century year
# year divided by 4 is a leap year
elif (year % 4 ==0) and (year % 100 != 0):
    print("{0} is a leap year".format(year))

# if not divided by both 400 (century year) and 4 (not century year)
# year is not leap year
else:
    print("{0} is not a leap year".format(year))        
           

2004 is a leap year


In [ ]:
# 6. Write a program to classify a triangle based on its sides' lengths.

In [27]:
side_1=int(input("Enter the side 1 length:"))
side_2=int(input("Enter the side 2 length:"))
side_3=int(input("Enter the side 3 length:"))
if(side_1==side_2):
    if(side_1==side_3):
        print("The triangle is equilateral .")
    else:
        print("The triangle is isosceles .")
else:
    if(side_1!=side_2):
        if(side_1==side_3):
            print("The triangle is isosceles .")
        else:
             print("The triangle is scalene.")

Enter the side 1 length: 12
Enter the side 2 length: 23
Enter the side 3 length: 34


The triangle is scalene.


In [ ]:
# 7. Build a program that determines the largest of three given numbers.

In [29]:
a=int(input("Enter the 1st number :"))
b=int(input("Enter the 2nd number :"))
c=int(input("Enter the 3rd number :"))
if(a>b):
    if(a>c):
        print(str(a)+" is the  largest  number ")
    else:  
        print(str(c)+" is the  largest  number ")
else:  
    if(b>c):  
        print(str(b)+" is the  largest  number ")
    else: 
        print(str(c)+" is the  largest  number ")
        

Enter the 1st number : 23
Enter the 2nd number : 5689
Enter the 3rd number : 7890


7890 is the  largest  number 


In [ ]:
# 8. Develop a program that checks whether a character is a vowel or a consonant.

In [32]:
character=input("Enter the character : ")
if(character=='a' or character=='e'  or character=='i' or character=='o' or character=='u'):
    print("The character is a vowel ")
else:
     print("The character is a consonant")         

Enter the character :  p


The character is a consonant


In [25]:
# 9. Create a program to calculate the total cost of a shopping cart based on discounts.

In [27]:
p=int(input('Enter purchase amount: '))

if p<=5000:
    dis=0
elif p>5000 and p<=10000:
    dis=(p-5000)*(10/100.0)
elif p>10000 and p<=20000:
    dis=(p-10000)*(20/100.0)
elif p>20000 and p<=30000:
    dis=(p-20000)*(30/100.0)
else:
    dis=(p-30000)*(40/100.0)

print('Discount Amount = {:.2f}'.format(dis))
print('Net Bill Amount = {:.2f}'.format(p-dis))

Enter purchase amount:  7600


Discount Amount = 260.00
Net Bill Amount = 7340.00


In [ ]:
# 10. Write a program that checks if a given number is even or odd.

In [35]:
num=int(input("Enter the number:"))
if(num%2==0):
    print("The number is even ")
else:
    print("The number is odd  ")

Enter the number: 2


The number is even 


In [ ]:
# 11. Write a program that calculates the roots of a quadratic equation.

In [58]:
print("Quadratic equation is ax^2 + bx+ c=0 ")
a=int(input("Enter the value of a which is coefficient of x^2 :"))
b=int(input("Enter the value of b which is coefficient of x:"))
c=int(input("Enter the value of c constant term:"))
x1=((-b)+((b)**2 -4*a*c)**0.5)/(2*a)
x2=((-b)-((b)**2 -4*a*c)**0.5)/(2*a)
print(f"Roots  of Quadratic equation {a}x^2 +{b}x +{c} = 0 are {x1} and {x2}")

Quadratic equation is ax^2 + bx+ c=0 


Enter the value of a which is coefficient of x^2 : 8
Enter the value of b which is coefficient of x: 3
Enter the value of c constant term: 5


Roots  of Quadratic equation 8x^2 +3x +5 = 0 are (-0.18749999999999994+0.7680128579652817j) and (-0.18750000000000006-0.7680128579652817j)


In [ ]:
# 12. Create a program that determines the day of the week based on the day number (1-7).

In [59]:
n=int(input("Enter the number:"))
if(n==1):
    print("It is Monday")
else:
    if(n==2):
         print("It is Tuesday")
    else:
        if(n==3):
            print("It is Wednesday")
        else:
                
                if(n==4):
                    print("It is Thrusday")
                else:
                    if(n==5):
                        print("It is Friday")
                    else:
                        if(n==6):
                            print("It is Saturday")
                        else:
                            print("It is Sunday")
        

Enter the number: 4


It is Thrusday


In [ ]:
# 13. Develop a program that calculates the factorial of a given number using recursion.

In [6]:
# Factorial of a number using recursion

def recur_factorial(n):
   
   if n == 1:
    return n
   else:
    return n*recur_factorial(n-1)

num = 7
# check if the number is negative
if num < 0:
    print("Sorry, factorial does not exist for negative numbers")
elif num == 0:
    print("The factorial of 0 is 1")
else:
    print("The factorial of", num, "is", recur_factorial(num))


The factorial of 7 is 5040


In [ ]:
# 14. Write a program to find the largest among three numbers without using the `max()` function.

In [ ]:
a=int(input("Enter the 1st number :"))
b=int(input("Enter the 2nd number :"))
c=int(input("Enter the 3rd number :"))
if(a>b):
    if(a>c):
        print(str(a)+" is the greatest number ")
    else:
        print(str(c)+" is the greatest number ")
else:
    if(b>c):
        print(str(b)+" is the greatest number ")
    else:
        print(str(c)+" is the greatest number ")
        

In [ ]:
# 15. Create a program that simulates a basic ATM transaction menu.

In [22]:
print('Welcome to SBI ATM')
restart=('Y')
chances = 3
balance = 100001
while chances >= 0:
    pin = int(input('Please Enter You 4 Digit Pin: '))
    if pin == (9714):
        print('You entered you pin Correctly\n')
        while restart not in ('n','NO','no','N'):
            print('Please Press 1 For Your Balance\n')
            print('Please Press 2 To Make a Withdrawl\n')
            print('Please Press 3 To Pay in\n')
            print('Please Press 4 To Return Card\n')
            option = int(input('What Would you like to choose?'))
            if option == 1:
                print('Your Balance is Rs.',balance,'\n')
                restart = input('Would You you like to go back? ')
                if restart in ('n','NO','no','N'):
                    print('Thank You')
                    break
            elif option == 2:
                option2 = ('y')
                withdrawl = int(input('How Much Would you like to withdraw?  for other enter 1: '))
                if withdrawl in list(range(1,100000)):
                    balance = balance - withdrawl
                    print ('\nYour Balance is now Rs.',balance)
                    restart = input('Would You you like to go back? ')
                    if restart in ('n','NO','no','N'):
                        print('Thank You')
                        break
                elif(withdrawl>balance):
                    print("You have insufficient bank balance")
                    restart = input('Would You you like to go back? ')
                    if restart in ('n','NO','no','N'):
                        print('Thank You')
                        break      
                          
                        
                elif withdrawl == 1:
                    withdrawl = float(input('Please Enter Desired amount:'))    

            elif option == 3:
                Pay_in = float(input('How Much Would You Like To Pay In? '))
                balance = balance + Pay_in
                print ('\nYour Balance is now Rs.',balance)
                restart = input('Would You you like to go back? ')
                if restart in ('n','NO','no','N'):
                    print('Thank You')
                    break
            elif option == 4:
                print('Please wait whilst your card is Returned...\n')
                print('Thank you for you service')
                break
            else:
                print('Please Enter a correct number. \n')
                restart = ('y')
    elif pin != ('9714'):
        print('Incorrect Password')
        chances = chances - 1
        if chances == 0:
            print('\nNo more tries')
            break

Welcome to SBI ATM


Please Enter You 4 Digit Pin:  1234


Incorrect Password


Please Enter You 4 Digit Pin:  9714


You entered you pin Correctly

Please Press 1 For Your Balance

Please Press 2 To Make a Withdrawl

Please Press 3 To Pay in

Please Press 4 To Return Card



What Would you like to choose? 1


Your Balance is Rs. 100001 



Would You you like to go back?  y


Please Press 1 For Your Balance

Please Press 2 To Make a Withdrawl

Please Press 3 To Pay in

Please Press 4 To Return Card



What Would you like to choose? 3
How Much Would You Like To Pay In?  100001



Your Balance is now Rs. 200002.0


Would You you like to go back?  y


Please Press 1 For Your Balance

Please Press 2 To Make a Withdrawl

Please Press 3 To Pay in

Please Press 4 To Return Card



What Would you like to choose? 2
How Much Would you like to withdraw?  for other enter 1:  200001


Please Press 1 For Your Balance

Please Press 2 To Make a Withdrawl

Please Press 3 To Pay in

Please Press 4 To Return Card



What Would you like to choose? 1


Your Balance is Rs. 200002.0 



Would You you like to go back?  y


Please Press 1 For Your Balance

Please Press 2 To Make a Withdrawl

Please Press 3 To Pay in

Please Press 4 To Return Card



What Would you like to choose? 1


Your Balance is Rs. 200002.0 



Would You you like to go back?  2


Please Press 1 For Your Balance

Please Press 2 To Make a Withdrawl

Please Press 3 To Pay in

Please Press 4 To Return Card



What Would you like to choose? 2
How Much Would you like to withdraw?  for other enter 1:  20001



Your Balance is now Rs. 180001.0


Would You you like to go back?  n


Thank You


Please Enter You 4 Digit Pin:  1234


Incorrect Password


Please Enter You 4 Digit Pin:  1234


Incorrect Password

No more tries


In [ ]:
# 16. Build a program that checks if a given string is a palindrome or not.

In [15]:
string=input("Enter the string:")
if(string==string[::-1]):
    print(f" Yes, {string} is a pallindrome ")
else:
     print(f" No, {string} is not a pallindrome ")
        

Enter the string: oppo


 Yes, oppo is a pallindrome 


In [ ]:
# 17. Write a program that calculates the average of a list of numbers, excluding the smallest and largest values.

In [20]:
def Average(lst):
    lst.sort()
    return (sum(lst)-lst[0]-lst[len(lst)-1])/(len(lst) -2)
 
lst = [10,20,30,1090,40]
average = Average(lst)
 
# Printing average of the list
print("Average of the list =", round(average, 2))

Average of the list = 30.0


In [ ]:
# 18. Develop a program that converts a given temperature from Celsius to Fahrenheit.

In [17]:
c=float(input("Enter the value of temperature in Celcius:"))
f=(9/5)*c +32
print("The value of "+str(c)+" degree celsius = " +str(f)+ " degree fahrenheit")

Enter the value of temperature in Celcius: 37.8


The value of 37.8 degree celsius = 100.03999999999999 degree fahrenheit


In [ ]:
# 19. Create a program that simulates a basic calculator for addition, subtraction, multiplication, and division.

In [12]:
num1=int(input("Enter the number 1:"))
num2=int(input("Enter the number 2:"))
op=input("Enter the operation")

match op:
    case '+':
        print(f"{num1}+{num2}={num1+num2}")
    case '-':
        print(f"{num1}-{num2}={num1-num2}")
    case '*':
        print(f"{num1} X {num2}={num1*num2}")
    case '/':
        print(f"{num1} /{num2}={num1/num2}")

Enter the number 1: 4
Enter the number 2: 2
Enter the operation -


4-2=2


In [ ]:
# 20. Write a program that determines the roots of a cubic equation using the Cardano formula.

In [3]:
from cmath import *

solutions = set()


def cbrt(polynomial):
    solution = set()
    root1 = polynomial ** (1 / 3)
    root2 = (polynomial ** (1 / 3)) * (-1 / 2 + (sqrt(3) * 1j) / 2)
    root3 = (polynomial ** (1 / 3)) * (-1 / 2 - (sqrt(3) * 1j) / 2)
    solution.update({root1, root2, root3})
    return solution


print('ax^3+bx^2+cx+d=0')
print("Enter the coefficients a,b,c and constant d of cubic equation each separated by space:")
a, b, c, d = map(complex, input().split())

if a != 0:
    p = (3 * a * c - b ** 2) / (3 * a ** 2)
    q = (2 * b ** 3 - 9 * a * b * c + 27 * a ** 2 * d) / (27 * a ** 3)
    alpha = cbrt(-q / 2 + sqrt((q / 2) ** 2 + (p / 3) ** 3))
    beta = cbrt(-q / 2 - sqrt((q / 2) ** 2 + (p / 3) ** 3))
    for i in alpha:
        for j in beta:
            if abs((i * j) + p / 3) <= 0.00001:
                x = i + j - b / (3 * a)
                solutions.add(x)

elif b != 0:
    D = c ** 2 - 4 * b * d
    solutions.add((-c - sqrt(D)) / 2 * b)
    solutions.add((-c + sqrt(D)) / 2 * b)

elif c != 0:
    solutions.add(-d / c)

elif d == 0:
    solutions.add("True")

else:
    solutions.add("False")

print(solutions)



ax^3+bx^2+cx+d=0
Enter the coefficients a,b,c and constant d of cubic equation each separated by space:


 0 1 3 2


{(-2+0j), (-1+0j)}


In [ ]:
# 21. Create a program that calculates the income tax based on the user's income and tax brackets.

In [28]:
def calculate(amount, percent):
	return (amount * percent) / 100

def calculate_income_tax(total_income:
						float) -> float:

	if total_income <= 250000:
		return 0
	elif total_income <= 500000:
		return calculate(total_income -
						250000, 5)
	elif total_income <= 750000:
		return calculate(total_income -
						500000, 10) + 12500
	elif total_income <= 1000000:
		return calculate(total_income -
						750000, 15) + 37500
	elif total_income <= 1250000:
		return calculate(total_income -
						1000000, 20) + 75000
	elif total_income <= 1500000:
		return calculate(total_income -
						1250000, 25) + 125000
	else:
		return calculate(total_income -
						1500000, 30) + 187500


if __name__ == '__main__':
	total_income = float(input("What's your\tannual income? : "))
	tax = calculate_income_tax(total_income)
	print(f"Total tax applicable at \t ₹{total_income} is ₹{tax}")


What's your	annual income? :  700000


Total tax applicable at 	 ₹700000.0 is ₹32500.0


In [ ]:
# 22. Write a program that simulates a rock-paper-scissors game against the computer.

In [18]:
import random
your_choice= input("Enter a choice out of  [rock, paper, scissors]: ")
possible_choices= ["rock", "paper", "scissors"]
computer_choice= random.choice(possible_choices)
if(your_choice==computer_choice):
    print("Congratulations!  You entered right guess")
else:
     print("Oops!  Wrong guess.")
print(f"You chose {your_choice}, computer chose {computer_choice}")

Enter a choice out of  [rock, paper, scissors]:  paper


Congratulations!  You entered right guess
You chose paper, computer chose paper


In [ ]:
# 23. Develop a program that generates a random password based on user preferences (length, complexity).

In [30]:
import string
import random
 
# Getting password length
length = int(input("Enter password length: "))
 
print('''Choose character set for password from these :
         1. Digits
         2. Letters
         3. Special characters
         4. Exit''')
 
characterList = ""
 
# Getting character set for password
while(True):
    choice = int(input("Pick a number "))
    if(choice == 1):
         
        # Adding letters to possible characters
        characterList += string.ascii_letters
    elif(choice == 2):
         
        # Adding digits to possible characters
        characterList += string.digits
    elif(choice == 3):
         
        # Adding special characters to possible
        # characters
        characterList += string.punctuation
    elif(choice == 4):
        break
    else:
        print("Please pick a valid option!")
 
    password = []
 
    for i in range(length):
   
    # Picking a random character from our
    # character list
       randomchar = random.choice(characterList)
     
    # appending a random character to password
       password.append(randomchar)
 
 # printing password as a string
print("The random password is " + "".join(password))


Enter password length:  8


Choose character set for password from these :
         1. Digits
         2. Letters
         3. Special characters
         4. Exit


Pick a number  2
Pick a number  1
Pick a number  3
Pick a number  4


The random password is m]LfW!#T


In [ ]:
# 24. Create a program that implements a simple text-based adventure game with branching scenarios.

In [103]:
answer_yes = ["Yes", "Y", "yes", "y"]
answer_no = ["No", "N", "no", "n"]

print("""
WELCOME! LET'S START THE ADVENTURE

You are standing outside of your house and you see a man running towards you and asking for urgent shelter.

Will you provide shelter to him. (Yes / No)
""")

ans1 = input(">>")

if ans1 in answer_yes:
    print("\nAfter 2 minutes, the Police came to your house, and ask you that whether the thief is in your house or not. Will you say (Yes / No)\n")

    ans2 = input(">>")

    if ans2 in answer_yes:
        print("\nYou are an honest person. He was a thief & You won the Game")

    elif ans2 in answer_no:
        print("\nYou helped a thief. Now, go to Jail. GAME OVER")

    else:
        print("\nYou typed the wrong input. GOODBYE!")

elif ans1 in answer_no:
    print("\nNow, he is trying to kill you. Will, you knock him down? (Yes / No)\n")

    ans3 = input(">>")

    if ans3 in answer_yes:
        print("\nCongrats! He was a thief & You helped the police to catch him with your bravery.")

    elif ans3 in answer_no:
        print("\nSorry! You are dead. He was a thief & He killed you. GAME OVER")

    else:
        print("\nYou typed the wrong input. GOODBYE!")

else:
    print("\nYou typed the wrong input. GOODBYE!")


WELCOME! LET'S START THE ADVENTURE

You are standing outside of your house and you see a man running towards you and asking for urgent shelter.

Will you provide shelter to him. (Yes / No)



>> n



Now, he is trying to kill you. Will, you knock him down? (Yes / No)



>> y



Congrats! He was a thief & You helped the police to catch him with your bravery.


In [ ]:
# 25. Build a program that solves a linear equation  for x, considering different cases.

In [107]:
print("For linear equation of type ax+by=c\n")

# importing library sympy
from sympy import symbols, Eq, solve

# defining symbols used in equations
# or unknown variables
x, y = symbols('x,y')

# defining equations
eq1 = Eq((x+y), 1)
print("Equation 1:")
print(eq1)
eq2 = Eq((x-y), 1)
print("Equation 2")
print(eq2)

# solving the equation
print("Values of 2 unknown variable are as follows:")

print(solve((eq1, eq2), (x, y)))


print("\nFor linear equation of type ax+by+cz=d\n")

# importing library sympy
from sympy import symbols, Eq, solve

# defining symbols used in equations
# or unknown variables
x, y, z = symbols('x,y,z')

# defining equations
eq1 = Eq((x+y+z), 1)
print("Equation 1:")
print(eq1)

eq2 = Eq((x-y+2*z), 1)
print("Equation 2")
print(eq2)

eq3 = Eq((2*x-y+2*z), 1)
print("Equation 3")

# solving the equation and printing the
# value of unknown variables
print("Values of 3 unknown variable are as follows:")
print(solve((eq1, eq2, eq3), (x, y, z)))


For linear equation of type ax+by=c

Equation 1:
Eq(x + y, 1)
Equation 2
Eq(x - y, 1)
Values of 2 unknown variable are as follows:
{x: 1, y: 0}

For linear equation of type ax+by+cz=d

Equation 1:
Eq(x + y + z, 1)
Equation 2
Eq(x - y + 2*z, 1)
Equation 3
Values of 3 unknown variable are as follows:
{x: 0, y: 1/3, z: 2/3}


In [1]:
# 26. Write a program that simulates a basic quiz game with multiple-choice questions and scoring.

In [39]:
from string import ascii_lowercase

QUESTIONS = {
    "Which is national bird of India": [
        "Peacock", "Crow", "Eagle", "Swan",
    ],
    "Which is most populated country in the world presently in 2023?": [
        "India",
        "USA",
        "UK",
        "China",
    ],
}

num_correct = 0
for num, (question, alternatives) in enumerate(QUESTIONS.items(), start=1):
    print(f"\nQuestion {num}:")
    print(f"{question}?")
    correct_answer = alternatives[0]
    labeled_alternatives = dict(zip(ascii_lowercase, sorted(alternatives)))
    for label, alternative in labeled_alternatives.items():
        print(f"  {label}) {alternative}")

    answer_label = input("\nChoice? ")
    answer = labeled_alternatives.get(answer_label)
    if answer == correct_answer:
        num_correct += 1
        print("Correct! ")
    else:
        print(f"The answer is {correct_answer!r}, not {answer!r}")

print(f"\nYou got {num_correct} correct out of {num} questions")


Question 1:
Which is national bird of India?
  a) Crow
  b) Eagle
  c) Peacock
  d) Swan



Choice?  c


Correct! 

Question 2:
Which is most populated country in the world presently in 2023??
  a) China
  b) India
  c) UK
  d) USA



Choice?  b


Correct! 

You got 2 correct out of 2 questions


In [3]:
# 27. Develop a program that determines whether a given year is a prime number or not.

In [5]:
num = 17
# If given number is greater than 1
if num > 1:
	# Iterate from 2 to n / 2
	for i in range(2, int(num/2)+1):
		# If num is divisible by any number between
		# 2 and n / 2, it is not prime
		if (num % i) == 0:
			print(num, "is not a prime number")
			break
	else:
		print(num, "is a prime number")
else:
	print(num, "is not a prime number")


17 is a prime number


In [ ]:
# 28. Create a program that sorts three numbers in ascending order using conditional statements.

In [101]:
a = float(input("Enter a: "))
b = float(input("Enter b: "))
c = float(input("Enter c: "))
if a > c:
    a = a + c
    c = a - c
    a = a - c  
if a > b:
    a = a + b
    b = a - b
    a = a - b
if b > c:
    b = b + c
    c = b - c
    b = b - c
print (a, "<", b, "<", c)

Enter a:  1
Enter b:  45
Enter c:  2


1.0 < 2.0 < 45.0


In [ ]:
# 29. Build a program that determines the roots of a quartic equation using numerical methods.

In [100]:
print("Quadratic equation is ax^2 + bx+ c=0 ")
a=int(input("Enter the value of a which is coefficient of x^2 :"))
b=int(input("Enter the value of b which is coefficient of x:"))
c=int(input("Enter the value of c constant term:"))
x1=((-b)+((b)**2 -4*a*c)**0.5)/(2*a)
x2=((-b)-((b)**2 -4*a*c)**0.5)/(2*a)
print(f"Roots  of Quadratic equation {a}x^2 +{b}x +{c} = 0 are {x1} and {x2}")

Quadratic equation is ax^2 + bx+ c=0 


Enter the value of a which is coefficient of x^2 : 1
Enter the value of b which is coefficient of x: 3
Enter the value of c constant term: 2


Roots  of Quadratic equation 1x^2 +3x +2 = 0 are -1.0 and -2.0


In [ ]:
# 30. Write a program that calculates the BMI (Body Mass Index) and provides health recommendations based on the user's input.

In [99]:
h=float(input("Enter the height in metres : "))
w=float(input("Enter the weight in kgs  :"))
bmi=w/(h**2)
print("Your BMI is",bmi)
if(bmi<18.5):
    print("You are underweight")
    print("You must take care of health and eat have sufficient nutrients intake in your diet ")
    
elif(bmi>=18.5 and bmi<25):
    print("You are normal")
    print("You are healthy and be consistent in maintaing good health that you possess now ") 
    
elif(bmi>=25 and bmi<30):
    print("You are overweight")
    print("Reduce overeating habit.Exercise daily and burn calories on daily basis.") 
    print("Consult doctor also for gaining better health and become fit")
    
elif(bmi>=30):
    print("You are obese")
    print("Immediately consult a doctor for treatement and getting health advice otherwise you may suffer dangerous consequences of neglecting health")
    

Enter the height in metres :  1.92
Enter the weight in kgs  : 79


Your BMI is 21.43012152777778
You are normal
You are healthy and be consistent in maintaing good health that you possess now 


In [ ]:
# 31. Create a program that validates a password based on complexity rules (length, characters, etc.).

In [59]:
# Python program to check validation of password
# Module of regular expression is used with search()
import re
password = "R@m@_f0rtu9e$"
flag = 0
while True:
	if (len(password)<=8):
		flag = -1
		break
	elif not re.search("[a-z]", password):
		flag = -1
		break
	elif not re.search("[A-Z]", password):
		flag = -1
		break
	elif not re.search("[0-9]", password):
		flag = -1
		break
	elif not re.search("[_@$]" , password):
		flag = -1
		break
	elif re.search("\s" , password):
		flag = -1
		break
	else:
		flag = 0
		print("Valid Password")
		break

if flag == -1:
	print("Not a Valid Password ")


Valid Password


In [ ]:
# 32. Develop a program that performs matrix addition and subtraction based on user input.

In [2]:
import numpy as np
 
# importing numpy as np

a=int(input("Enter the value of a element of matrix A :"))
b=int(input("Enter the value of b element of matrix A:"))
c=int(input("Enter the value of c element of matrix A:"))
d=int(input("Enter the value of d element of matrix A :"))
e=int(input("Enter the value of e element of matrix B :"))
f=int(input("Enter the value of f element of matrix B :"))
g=int(input("Enter the value of g element of matrix B :"))
h=int(input("Enter the value of h element of matrix B :"))

# creating first matrix
A = np.array([[a, b], [c, d]])
 
# creating second matrix
B = np.array([[e, f], [g, h]])
 
print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)
 
# adding two matrix
print("Addition of two matrix")
print(np.add(A, B)) 

 
# subtracting two matrix
print("Subtraction of two matrix")
print(np.subtract(A, B))

Enter the value of a element of matrix A : 1
Enter the value of b element of matrix A: 2
Enter the value of c element of matrix A: 3
Enter the value of d element of matrix A : 4
Enter the value of e element of matrix B : 5
Enter the value of f element of matrix B : 6
Enter the value of g element of matrix B : 7
Enter the value of h element of matrix B : 8


Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[5 6]
 [7 8]]
Addition of two matrix
[[ 6  8]
 [10 12]]
Subtraction of two matrix
[[-4 -4]
 [-4 -4]]


In [ ]:
# 33. Write a program that calculates the greatest common divisor (GCD) of two numbers using the Euclidean algorithm.

In [6]:
import math
 
# prints 12
print("The gcd of 60 and 48 is : ", end="")
print(math.gcd(60, 48))

The gcd of 60 and 48 is : 12


In [ ]:
# 34. Build a program that performs matrix multiplication using nested loops and conditional statements.

In [76]:
# Program to multiply two matrices using nested loops

# 3x3 matrix
X = [[12,7,3],
     [4 ,5,6],
     [7 ,8,9]]
# 3x4 matrix
Y = [[5,8,1,2],
     [6,7,3,0],
     [4,5,9,1]]
# result is 3x4
result = [[0,0,0,0],
          [0,0,0,0],
          [0,0,0,0]]

# iterate through rows of X
for i in range(len(X)):
   # iterate through columns of Y
   for j in range(len(Y[0])):
       # iterate through rows of Y
       for k in range(len(Y)):
        result[i][j] += X[i][k] * Y[k][j]

for r in result:
    print(r)


[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


In [10]:
# 35. Create a program that simulates a basic text-based tic-tac-toe game against the computer.

In [ ]:
# Tic-Tac-Toe Program using
# random number in Python

# importing all necessary libraries
import numpy as np
import random
from time import sleep

# Creates an empty board


def create_board():
	return(np.array([[0, 0, 0],
					[0, 0, 0],
					[0, 0, 0]]))

# Check for empty places on board


def possibilities(board):
	l = []

	for i in range(len(board)):
		for j in range(len(board)):

			if board[i][j] == 0:
				l.append((i, j))
	return(l)

# Select a random place for the player


def random_place(board, player):
	selection = possibilities(board)
	current_loc = random.choice(selection)
	board[current_loc] = player
	return(board)

# Checks whether the player has three
# of their marks in a horizontal row


def row_win(board, player):
	for x in range(len(board)):
		win = True

		for y in range(len(board)):
			if board[x, y] != player:
				win = False
				continue

		if win == True:
			return(win)
	return(win)

# Checks whether the player has three
# of their marks in a vertical row


def col_win(board, player):
	for x in range(len(board)):
		win = True

		for y in range(len(board)):
			if board[y][x] != player:
				win = False
				continue

		if win == True:
			return(win)
	return(win)

# Checks whether the player has three
# of their marks in a diagonal row


def diag_win(board, player):
	win = True
	y = 0
	for x in range(len(board)):
		if board[x, x] != player:
			win = False
	if win:
		return win
	win = True
	if win:
		for x in range(len(board)):
			y = len(board) - 1 - x
			if board[x, y] != player:
				win = False
	return win

# Evaluates whether there is
# a winner or a tie


def evaluate(board):
	winner = 0

	for player in [1, 2]:
		if (row_win(board, player) or
				col_win(board, player) or
				diag_win(board, player)):

			winner = player

	if np.all(board != 0) and winner == 0:
		winner = -1
	return winner

# Main function to start the game


def play_game():
	board, winner, counter = create_board(), 0, 1
	print(board)
	sleep(2)

	while winner == 0:
		for player in [1, 2]:
			board = random_place(board, player)
			print("Board after " + str(counter) + " move")
			print(board)
			sleep(2)
			counter += 1
			winner = evaluate(board)
			if winner != 0:
				break
	return(winner)


# Driver Code
print("Winner is: " + str(play_game()))


[[0 0 0]
 [0 0 0]
 [0 0 0]]
Board after 1 move
[[0 0 0]
 [0 0 0]
 [0 0 1]]
Board after 2 move
[[0 0 0]
 [0 2 0]
 [0 0 1]]
Board after 3 move
[[0 0 0]
 [0 2 1]
 [0 0 1]]
Board after 4 move
[[0 0 2]
 [0 2 1]
 [0 0 1]]
Board after 5 move
[[0 0 2]
 [0 2 1]
 [1 0 1]]
Board after 6 move
[[2 0 2]
 [0 2 1]
 [1 0 1]]
Board after 7 move
[[2 0 2]
 [1 2 1]
 [1 0 1]]
Board after 8 move
[[2 2 2]
 [1 2 1]
 [1 0 1]]
Winner is: 2


In [ ]:
# 36. Write a program that generates Fibonacci numbers up to a specified term using iterative methods.

In [69]:
n = int(input("Enter the number of terms upto which fibonacci series you want : "))
first,second=0,1
print("fibonacci series  : ")
for i in range(0,n):
    if i<=1:
        result=i
    else:
      result = first + second;
      first = second;
      second = result;
    print(result,end=" ")

Enter the number of terms upto which fibonacci series you want :  11


fibonacci series  : 
0 1 1 2 3 5 8 13 21 34 55 

In [ ]:
# 38. Create a program that generates a calendar for a given month and year using conditional statements.

In [56]:
# Python code to print Calendar
# Without use of Calendar module

mm = 9
yy = 2023

month ={1:'January', 2:'February', 3:'March',
		4:'April', 5:'May', 6:'June', 7:'July',
		8:'August', 9:'September', 10:'October',
		11:'November', 12:'December'}

# code below for calculation of odd days
day =(yy-1)% 400
day = (day//100)*5 + ((day % 100) - (day % 100)//4) + ((day % 100)//4)*2
day = day % 7

nly =[31, 28, 31, 30, 31, 30,
	31, 31, 30, 31, 30, 31]
ly =[31, 29, 31, 30, 31, 30,
	31, 31, 30, 31, 30, 31]
s = 0

if yy % 4 == 0:
	for i in range(mm-1):
		s+= ly[i]
else:
	for i in range(mm-1):
		s+= nly[i]

day += s % 7
day = day % 7

# variable used for white space filling
# where date not present
space =''
space = space.rjust(2, ' ')

# code below is to print the calendar
print(month[mm], yy)
print('Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa')

if mm == 9 or mm == 4 or mm == 6 or mm == 11:
	for i in range(31 + day):
		
		if i<= day:
			print(space, end =' ')
		else:
			print("{:02d}".format(i-day), end =' ')
			if (i + 1)% 7 == 0:
				print()
elif mm == 2:
	if yy % 4 == 0:
		p = 30
	else:
		p = 29
		
	for i in range(p + day):
		if i<= day:
			print(space, end =' ')
		else:
			print("{:02d}".format(i-day), end =' ')
			if (i + 1)% 7 == 0:
				print()
else:
	for i in range(32 + day):
		
		if i<= day:
			print(space, end =' ')
		else:
			print("{:02d}".format(i-day), end =' ')
			if (i + 1)% 7 == 0:
				print()


September 2023
Su Mo Tu We Th Fr Sa
               01 02 
03 04 05 06 07 08 09 
10 11 12 13 14 15 16 
17 18 19 20 21 22 23 
24 25 26 27 28 29 30 


In [ ]:
# 39. Build a program that simulates a basic text-based blackjack game against the computer.

In [58]:
import random

card_categories = ['Hearts', 'Diamonds', 'Clubs', 'Spades']
cards_list = ['Ace', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'Jack', 'Queen', 'King']
deck = [(card, category) for category in card_categories for card in cards_list]

def card_value(card):
	if card[0] in ['Jack', 'Queen', 'King']:
		return 10
	elif card[0] == 'Ace':
		return 11
	else:
		return int(card[0])

random.shuffle(deck)
player_card = [deck.pop(), deck.pop()]
dealer_card = [deck.pop(), deck.pop()]

while True:
	player_score = sum(card_value(card) for card in player_card)
	dealer_score = sum(card_value(card) for card in dealer_card)
	print("Cards Player Has:", player_card)
	print("Score Of The Player:", player_score)
	print("\n")
	choice = input('What do you want? ["play" to request another card, "stop" to stop]: ').lower()
	if choice == "play":
		new_card = deck.pop()
		player_card.append(new_card)
	elif choice == "stop":
		break
	else:
		print("Invalid choice. Please try again.")
		continue

	if player_score > 21:
		print("Cards Computer Has:", dealer_card)
		print("Score Of The Computer:", dealer_score)
		print("Cards Player Has:", player_card)
		print("Score Of The Player:", player_score)
		print("Computer wins (Player Loss Because Player Score is exceeding 21)")
		break

while dealer_score < 17:
	new_card = deck.pop()
	dealer_card.append(new_card)
	dealer_score += card_value(new_card)

print("Cards Computer Has:", dealer_card)
print("Score Of The Computer:", dealer_score)
print("\n")

if dealer_score > 21:
	print("Cards Computer Has:", dealer_card)
	print("Score Of The Computer:", dealer_score)
	print("Cards Player Has:", player_card)
	print("Score Of The Player:", player_score)
	print("Player wins (Computer Loss Because Computer Score is exceeding 21)")
elif player_score > dealer_score:
	print("Cards Computer Has:", dealer_card)
	print("Score Of The Computer:", dealer_score)
	print("Cards Player Has:", player_card)
	print("Score Of The Player:", player_score)
	print("Player wins (Player Has High Score than computer)")
elif dealer_score > player_score:
	print("Cards Computer  Has:", dealer_card)
	print("Score Of The Dealer:", dealer_score)
	print("Cards Player Has:", player_card)
	print("Score Of The Player:", player_score)
	print("Computer wins (Computer Has High Score than Player)")
else:
	print("Cards Computer Has:", dealer_card)
	print("Score Of The Computer:", dealer_score)
	print("Cards Player Has:", player_card)
	print("Score Of The Player:", player_score)
	print("It's a tie.")


Cards Player Has: [('10', 'Spades'), ('4', 'Diamonds')]
Score Of The Player: 14




What do you want? ["play" to request another card, "stop" to stop]:  play


Cards Player Has: [('10', 'Spades'), ('4', 'Diamonds'), ('Queen', 'Clubs')]
Score Of The Player: 24




What do you want? ["play" to request another card, "stop" to stop]:  play


Cards Computer Has: [('9', 'Clubs'), ('4', 'Hearts')]
Score Of The Computer: 13
Cards Player Has: [('10', 'Spades'), ('4', 'Diamonds'), ('Queen', 'Clubs'), ('8', 'Hearts')]
Score Of The Player: 24
Computer wins (Player Loss Because Player Score is exceeding 21)
Cards Computer Has: [('9', 'Clubs'), ('4', 'Hearts'), ('Ace', 'Hearts')]
Score Of The Computer: 24


Cards Computer Has: [('9', 'Clubs'), ('4', 'Hearts'), ('Ace', 'Hearts')]
Score Of The Computer: 24
Cards Player Has: [('10', 'Spades'), ('4', 'Diamonds'), ('Queen', 'Clubs'), ('8', 'Hearts')]
Score Of The Player: 24
Player wins (Computer Loss Because Computer Score is exceeding 21)


In [ ]:
# 40. Write a program that generates the prime factors of a given number using trial division.

In [66]:
# Python program to print prime factors

import math

# A function to print all prime factors of
# a given number n
def primeFactors(n):
	
	# Print the number of two's that divide n
	while n % 2 == 0:
		print(2)
		n = n // 2
		
	# n must be odd at this point
	# so a skip of 2 ( i = i + 2) can be used
	for i in range(3,int(math.sqrt(n))+1,2):
		
		# while i divides n , print i ad divide n
		while n % i== 0:
			print(i)
			n = n // i
			
	# Condition if n is a prime
	# number greater than 2
	if n > 2:
		print(n)
		

n = 124
primeFactors(n)

2
2
31
